In [30]:
# program 1: Calculate total weekly energy from a list
daily_Kwh = [400,200,100,800,200,400]
total_energy = sum(daily_Kwh)
print("total energy used:",total_energy,"Kwh")

total energy used: 2100 Kwh

In [31]:
# program 2: store building usage data
building_usage = {
    "cse" : 400,
    "hostel" : 200
}
print("hostel used:",building_usage["hostel"],"Kwh")

hostel used: 200 Kwh

In [32]:
#program 3:
def calculate_bill(kwh,rate_per_unit):
  return kwh * rate_per_unit

todays_bill = calculate_bill(400,8)
print("Today's estimated bill is Rs.",todays_bill)

Today's estimated bill is Rs. 3200

In [33]:
# program 4: Read a file line by line
with open("campus_energy.csv","r") as file:
    for line in file.readlines():
         print(line.strip())

﻿Date,Building, KWh used,hours_usage
5/10/2026,cse,400,120
6/10/2026,civil,850,222
7/10/2026,mech,400,111
8/10/2026,hostel,350,328
10/10/2026,cse,500,261
11/10/2026,cyber,600,123
12/10/2026,hostle,300,217
13/10/2026,civil,550,127
14/10/2026,mech,700,163

In [34]:
# import the pandas library
import pandas as pd

#load the dataset you created
df = pd.read_csv('camous_energy.csv')

#Display the first few rows of the data
print("Here is the raw data:")
display(df.head())

#Group the data to see total usage per building
building_totals = df.groupby('Building')['Kwh_Used'].sum()
print("\nTotal usage per building:")
print(building_totals)

#Generate a statistical summary(avg,max,min) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  KWh used  hours_usage
0   5/10/2026      cse       400          120
1   6/10/2026    civil       850          222
2   7/10/2026     mech       400          111
3   8/10/2026   hostel       350          328
4  10/10/2026      cse       500          261

Total usage per building:
Building
civil     1400
cse        900
cyber      600
hostel     350
hostle     300
mech      1100
Name: KWh used, dtype: int64

Statistical Summary:

         KWh used  hours_usage
count    9.000000     9.000000
mean   516.666667   185.777778
std    178.535711    75.833333
min    300.000000   111.000000
25%    400.000000   123.000000
50%    500.000000   163.000000
75%    600.000000   222.000000
max    850.000000   328.000000

In [35]:
# create the README.md file and write a message inside it
with open("README.md","w") as file:
     file.write("#smart Campus Energy Project\n")
     file.write("this repository contains my week 1 hands on python and pandas assignments.\n")
     file.write("Created by: [Meghana u]")

print("README.md has been successfully created")

README.md has been successfully created